export { default as netflix } from './Netflix-Symbol.png'
export { default as disney } from './disney+.jpg'
export { default as hbo } from './hbo+.webp'
export { default as prime } from './prime.jpg'
export { default as hulu } from './hulu.webp'
