import '../styles/globals.css';
import NavBar from '@/components/navbar/NavBar';
import type { Metadata } from 'next'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Footer from '@/components/footer/Footer';

export const metadata: Metadata = {
  title: 'Popcorn MovieHub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <NavBar />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  )
}
