import '../styles/globals.css';
import NavBar from '@/components/navbar/NavBar';
import type { Metadata } from 'next'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Footer from '@/components/footer/Footer';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import MNavbar from '@/components/navbar/mobile Navbar/MNavbar';

export const metadata: Metadata = {
  title: 'Popcorn MovieHub',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <NavBar />
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          {children}
          <Footer />
          <MNavbar />
        </body>
      </UserProvider>
    </html>
  )
}
